# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  github-poxx:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT}}
  npm-npmjs:
    type: npm-registry
    url: https://cloudbolt-499620025628.d.codeartifact.us-east-1.amazonaws.com/npm/cloudbolt-npm/
    username: aws
    password: ${{secrets.CODEARTIFACT_NPM_AUTH_TOKEN}}
updates:
  - package-ecosystem: "" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/static_src/" # Location of package manifests
    allow:
      - dependency-type: "production"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/src/static_src/vue" # Location of package manifests
    allow:
      - dependency-type: "production"
    registries: "*"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
