name: 'Publish to JS-SDK'

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to publish (e.g. v0.6.11)"
        required: true
      package_path:
        description: "Path to the package (e.g. packages/js-sdk or .)"
        default: "packages/js-sdk"
      dry_run:
        description: "Dry run publish"
        type: boolean
        default: false
      npm_dist_tag:
        description: "npm dist-tag (latest, next, beta...)"
        default: "latest"

jobs:
  publish-to-npm:
    name: Publish to JS-SDK
    runs-on: 'ubuntu-latest'
    environment: Production
    env:
      TAG: ${{ github.event_name == 'release' && github.event.release.tag_name || inputs.tag }}
      PACKAGE_PATH: ${{ inputs.package_path || 'packages/js-sdk' }}
      DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry_run || vars.DRY_RUN }}
      NPM_DIST_TAG: ${{ inputs.npm_dist_tag || 'latest' }}

    steps:
      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TAG }}
          fetch-depth: 0
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup, Authenticate, and Install
        uses: ./.github/actions/setup-runner

      - run: npm run test

      - run: npm run build

      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          dry-run: ${{ vars.DRY_RUN }}
